### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by amiltonwong** [fvisin/dataset_loaders#13]
Hi, @fvisin ,

Thanks for releasing this useful package. I followed the install instruction. However, when I import `dataser_loaders`, I got the following error in parallel_loader.py as the following. (Currently, I only need to load Camvid dataset)

```
(tf_1.0) root@milton-All-Series:/data/code/dataset_loaders/dataset_loaders# python
Python 3.5.2 | packaged by conda-forge | (default, Jan 19 2017, 15:28:33) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dataset_loaders
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/code/dataset_loaders/dataset_loaders/__init__.py", line 3, in <module>
    from images.camvid import CamvidDataset  # noqa
  File "/data/code/dataset_loaders/dataset_loaders/images/camvid.py", line 5, in <module>
    from dataset_loaders.parallel_loader import ThreadedDataset
  File "/data/code/dataset_loaders/dataset_loaders/parallel_loader.py", line 519
    raise data_batch[0], data_batch[1], data_batch[2]
                       ^
SyntaxError: invalid syntax
```

Here is the setting in my config.ini

```
[camvid]
shared_path = /data/code/SegNet-Tutorial/
```

The Camvid dataset is located in the following folder structures (screen):
![camvid_dataset](https://user-images.githubusercontent.com/2517000/27012564-6d927288-4f04-11e7-9419-00248a710569.png)

**Comment by amiltonwong** [comment]
I use python 3.5

**Comment by fvisin** [comment]
Hi @amiltonwong , thank you for checking out our framework.
Unfortunately we do not support python 3 at the moment. I don't know how long it would take to make it python 3 compatible, but unfortunately we don't plan to work on that in the near future at the moment.

Contributions in this direction are very welcome though, if you want to give it a try!
